### PR TITLE
basic song title cleaning

### PR DESCRIPTION
**Pull request by miguelBinpar**
A basic first approach for #36

### CODE REVIEW

**Comment by alyyousuf7** [comment]
I think the cleaning should not happen here, but in the Lyrics Search function, it's a separate repository: https://github.com/ShyykoSerhiy/vscode-spotify-lyrics/blob/master/app.ts

If we do the cleaning here, we'll break the functionality for other Lyrics searching servers that other people might be using.

**Comment by miguelBinpar** [comment]
I agree. My bad, I didn't check the whole lyrics trace, but it will definitely suit better inside lyrics search function

**Comment by miguelBinpar** [comment]
I'm closing as it's the regular expression idea is now being used on https://github.com/ShyykoSerhiy/vscode-spotify-lyrics/commit/ddebc0bece94cbd41fcb14fb9c1926f675286e9f

**Comment by ShyykoSerhiy** [comment]
@miguelBinpar dcad29a5be136e76202a8c2e4c542aa396a2e475

**Comment by miguelBinpar** [comment]
@ShyykoSerhiy thank you very much! Glad to help!

**Pull request closed without merging**
