### PR TITLE
vscode-spotify-marquee-widget

### PR DESCRIPTION
**Pull request by lorenzejay**
This pull request integrates your vscode-spotify extension onto the [Marquee Widget Ecosystem](https://marquee.stateful.com/docs/customWidgets). With the provided Spotify data provided, we created a minimalistic user interface that mirrors the same original functionality with just a minor tweak to extension.ts.   

Only one small change was made to your extension - 
Extension.ts - returns a Marquee Widget instance in order to port over 
```
return {
    marquee: {
      setup: (
        tangle: Client<{
          track: ITrack;
          playerState: IPlayerState;
          loginState: ILoginState;
        }>
      ) => {
        getStore(context.globalState).subscribe(() => {
          const { track, playerState } = getState();
          tangle.emit('track', track);
          tangle.emit("playerState", playerState);
        });
      },
    },
  };
```

The newly added files were to create the UI and do not interfere with the pre-existing codebase. 

Screen Shot 2022-04-05 at 11 25 44 AM

Code changes on actions.ts and local.ts were to remove type errors on error catch. Added error type `e: any` type to clear errors.

### CODE REVIEW

**Comment by ShyykoSerhiy** [comment]
This looks great 👌. I'll go through the PR this weekend and release a new version.

**Comment by lorenzejay** [comment]
> This looks great 👌. I'll go through the PR this weekend and release a new version.

Thank you. I appreciate you taking the time. If you have any questions, feel free to let me know.

**Comment by lorenzejay** [comment]
hey @ShyykoSerhiy. I hope you were able to run the pull request on your end. If you need any help or have any questions, feel free to message me.

**Comment by lorenzejay** [comment]
> This looks great 👌. I'll go through the PR this weekend and release a new version.

Hey @ShyykoSerhiy, some time has passed but is there any update on the PR?

**Comment by christian-bromann** [comment]
> This looks great 👌. I'll go through the PR this weekend and release a new version.

@ShyykoSerhiy any updates?

**Comment by lorenzejay** [comment]
Closing PR, please reference - 
https://github.com/ShyykoSerhiy/vscode-spotify/pull/182

**Pull request closed without merging**
