### PR TITLE
Feat/tslint

### PR DESCRIPTION
**Pull request by realbizkit**
--  `INFO: This is an oversized PR but it does not contain functional changes!` --

- Main purpose of changes: introducing `TS Lint` to the project
  -> helps keeping the code cleaner
  -> by enforcing rules (which can be easily customized later) on each commit, it helps contributors to be aligned with the project's coding guidelines
- Tools used:
  -> `husky`: manages git hooks to include them in versioning
  -> `lint-staged`: runs linters only on staged files which is much faster than running on whole project
- Added a package.json script "lint" which runs tslint for the whole project (can be handy)

- There are very small non-functional refactorings here and there, especially where the preset basic tslint rules enforced them. @ShyykoSerhiy make sure to validate them.

### CODE REVIEW

**Comment by ShyykoSerhiy** [comment]
@realbizkit, looks good. One note thought, why use tabs? 
I have a couple of problems with tabs:
1. Github doesn't show them properly.
Screen Shot 2019-04-21 at 4 05 17 PM
2. Typescript language server doesn't really works with tabs formatting https://github.com/Microsoft/TypeScript/issues/2306.

**Comment by realbizkit** [comment]
Started with spaces because I saw that many file had them, then I saw that some files had tabs as well and some had tabs by default. Since I rather use tabs, I set the rules that way, but it's totally up to you.

If you prefer spaces, I can change the rule, the point is to avoid mixed usage. One important question in that case: how many spaces per indentation? I think I saw 4.

**Comment by ShyykoSerhiy** [comment]
4 would be fine. Thanks for the PR. I've been meaning to do it for a long time.

**Comment by realbizkit** [comment]
Tabs converted back to spaces ;)

**Pull request merged**
