### PR TITLE
Feat/linux support

### PR DESCRIPTION
**Pull request by audstanley**
OK,

Sorry about that last pull request.

This has Next/Previous/VolumeUp/VolumeDown/MuteToggle/

Doesn't update status of Mute Yet, but I'll look into fixing that. :-)

### CODE REVIEW

**Comment by audstanley** [comment]
If you don't want the project master, make a feat/linuxSupport branch, and I can push to that if you want. :-)

or you could test on my fork.  Thanks for making this I've been wanting to contribute Linux Support for a VERY long time. Finally got around to it.

**Comment by ShyykoSerhiy** [comment]
Looks awesome. I'll test it out tomorrow and probably publish new version. 
cheers

**Comment by audstanley** [comment]
also i just realized that:
let sinkInputs = Array.prototype
let applications = Array.prototype

... are unused variables. so feel free to delete those lines. ill refrain from making another pull request.

**Comment by audstanley** [comment]
I'm going to close this pull request and open a new one with those unused variables deleted, and an update to the README (with a separate Linux table column)

**Pull request closed without merging**
