### PR TITLE
Feat/linux support

### PR DESCRIPTION
**Pull request by audstanley**
OK, this looks better.
:-)

### CODE REVIEW

**Comment by audstanley** [comment]
Did you test yet?  I've literally been working on my other projects inside of the debugger of the vs-code extension. lol, Don't make me wait brother. :-)

**Comment by audstanley** [comment]
Any update?  Let me know if you're having any issues.  I'm ready to help out.

**Comment by ShyykoSerhiy** [comment]
I'll publish today. Sry for long wait.

**Comment by audstanley** [comment]
No worries, and thanks :-) :100: .  Hey, you're an awesome programmer...

if you have some time, would you mind checking out a VSCode extension I'm working on?  It's a VSCode extension to connect to IRC servers.  My buddy and i just started it.  We're still learning vs-code extension building and typescript, but the idea is that when you launch the IRC extension, it will check your .git folder, and connect you to an IRC channel with the same convention.  So for example, my git username is audstanley, and the name of the project I'm working on currently is vscode-IRC, so the extension (on activation) will connect me to the server i put in my workspace settings (irc.freenode.net), then I get auto-connected to the channel #audstanley-vscode-IRC (because the URL of the .git/config [remote "origin"] repository url is https://www.github.com/audstanley/vscode-IRC). This way, if you clone a project, you get connected to the channel where devolopers are actively connected to...

Another example, if I launched the IRC extension, with irc.freenode.net as my main IRC server, and i was working on vscode-spotify, than I would connect to the channel: #ShyykoSerhiy-vscode-spotify.  This would be an amazing way to live chat with developers on projects that you are contributing to, plus I still love IRC, and there is no working IRC client as a VSCode extension.  The only one listed, doesn't work.

I'm thinking of building an express server as an endpoint, so that as long as you have activated the extension, it keeps running in the background. So you wont be relaunching a server connection every time you switch panels (i got the idea from Microsoft's Arduino extension, which launches an express server that you make POST requests to locally).  Let me know if you're interested.  I can add you as a collaborator.

**Pull request merged**
